Move templates to RHEL/CentOS/UBI 8
sclorg/rails-ex pull request #131
Opened 2020-08-28 03:48 UTC by yselkowitz

This has already been tested in image ecosystem:

https://github.com/openshift/cluster-samples-operator/pull/319

2020-09-02 12:54 UTC, hhorak requested changes
It seems to be worth updating the versions as well, otherwise LGTM.

2020-09-02 12:54 UTC, hhorak commented on openshift/templates/rails-postgresql-persistent.json
> +              "name": "ruby:2.5-ubi8"
Version 2.5 is not latest anymore. We can either use `2.7-ubi7` or `2.6-ubi8`

2020-09-02 12:54 UTC, hhorak commented on openshift/templates/rails-postgresql-persistent.json
> +                "name": "postgresql:10-el8"
Here as well, we can use `12-el8` that is already available.

2020-09-02 12:54 UTC, hhorak commented on openshift/templates/rails-postgresql-persistent.json
> +              "name": "ruby:2.5-ubi8"
Hm, maybe 2.6 for now before https://github.com/sclorg/rails-ex/pull/130 is tested properly.

2020-09-02 14:13 UTC, yselkowitz commented
Changes incorporated, please re-review.

2020-09-03 15:28 UTC, hhorak commented
Perfect, thanks.

2020-09-03 15:28 UTC, hhorak approved these changes

2020-09-03 15:28 UTC, merged